version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: educablog
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: educablog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  db_data:
