version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: educablog
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: educablog
    ports:
      - "5435:5432"  # Usar a porta 5435 no host
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    build: .
    environment:
      DATABASE_URL: postgresql://educablog:123456@localhost:5435/educablog?schema=public  # Usar a porta 5435
      JWT_SECRET: F6&uP!5m@6B0g3vR8kL*Q9z7D
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c", "npx prisma generate && npm start"]

volumes:
  db_data:
