services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: educablog
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: educablog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    build: .
    environment:
      DATABASE_URL: postgresql://educablog:123456@db:5432/educablog?schema=public
      JWT_SECRET: F6&uP!5m@6B0g3vR8kL*Q9z7D
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c", "sleep 10 && npx prisma generate && npm start"]

volumes:
  db_data:
