name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DOCKER }}
        run: |
          docker-compose run --rm app npx prisma migrate deploy

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DOCKER }}
        run: |
          docker-compose run --rm app npm test

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose down

      - name: Deploy to Production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DOCKER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker-compose up -d
